//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keeptrue.Conciliador.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Menu_lateral {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu_lateral() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Keeptrue.Conciliador.View.Menu-lateral", typeof(Menu_lateral).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;id&quot;: &quot;devolucoes&quot;,
        ///        &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///        &quot;isActive&quot;: true,
        ///        &quot;name&quot;: &quot;Análises&quot;,
        ///        &quot;link&quot;: &quot;#&quot;,
        ///        &quot;icon&quot;: &quot;glyphicon glyphicon-book&quot;,
        ///        &quot;subMenu&quot;: [.
        /// </summary>
        internal static string analises {
            get {
                return ResourceManager.GetString("analises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;associar&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: false,
        ///                &quot;name&quot;: &quot;Assorciar Grupo x CNPJ&quot;,
        ///                &quot;link&quot;: &quot;/Grupos/Associar&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string associar {
            get {
                return ResourceManager.GetString("associar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;id&quot;: &quot;cadastros&quot;,
        ///        &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///        &quot;isActive&quot;: true,
        ///        &quot;name&quot;: &quot;Cadastros&quot;,
        ///        &quot;link&quot;: &quot;#&quot;,
        ///        &quot;icon&quot;: &quot;glyphicon-edit&quot;,
        ///        &quot;subMenu&quot;: [.
        /// </summary>
        internal static string cadastros {
            get {
                return ResourceManager.GetString("cadastros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;cadmatriz&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Matriz&quot;,
        ///                &quot;link&quot;: &quot;/Empresa&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string cadmatriz {
            get {
                return ResourceManager.GetString("cadmatriz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;usuarios&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Usuários&quot;,
        ///                &quot;link&quot;: &quot;/Usuarios&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string cadusuarios {
            get {
                return ResourceManager.GetString("cadusuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;configApurCred&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Apuração de Crédito&quot;,
        ///                &quot;link&quot;: &quot;/Apuracao/Credito&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string configApurCred {
            get {
                return ResourceManager.GetString("configApurCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;configApurRec&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Apuração de Receita&quot;,
        ///                &quot;link&quot;: &quot;/Apuracao/Receita&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string configApurRec {
            get {
                return ResourceManager.GetString("configApurRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;configLogs&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Logs&quot;,
        ///                &quot;link&quot;: &quot;/_Logs/Index&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string configLogs {
            get {
                return ResourceManager.GetString("configLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;id&quot;: &quot;configuracoes&quot;,
        ///        &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///        &quot;isActive&quot;: true,
        ///        &quot;name&quot;: &quot;Configurações&quot;,
        ///        &quot;link&quot;: &quot;#&quot;,
        ///        &quot;icon&quot;: &quot;glyphicon glyphicon-list-alt&quot;,
        ///        &quot;subMenu&quot;: [.
        /// </summary>
        internal static string configuracoes {
            get {
                return ResourceManager.GetString("configuracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;id&quot;: &quot;cruzamentos&quot;,
        ///        &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///        &quot;isActive&quot;: true,
        ///        &quot;name&quot;: &quot;EFD&quot;,
        ///        &quot;link&quot;: &quot;#&quot;,
        ///        &quot;icon&quot;: &quot;glyphicon glyphicon-indent-right&quot;,
        ///        &quot;subMenu&quot;: [.
        /// </summary>
        internal static string cruzamentos {
            get {
                return ResourceManager.GetString("cruzamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;cruzcarga&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Carga&quot;,
        ///                &quot;link&quot;: &quot;/EFD/Carga&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string cruzcarga {
            get {
                return ResourceManager.GetString("cruzcarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;cruzlogs&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Logs&quot;,
        ///                &quot;link&quot;: &quot;/EFD/Logs&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string cruzlogs {
            get {
                return ResourceManager.GetString("cruzlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;cruztarefas&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Tarefas&quot;,
        ///                &quot;link&quot;: &quot;/EFD/Tarefas&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string cruztarefa {
            get {
                return ResourceManager.GetString("cruztarefa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;id&quot;: &quot;dashboard&quot;,
        ///        &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///        &quot;isActive&quot;: false,
        ///        &quot;name&quot;: &quot;Dashboard&quot;,
        ///        &quot;link&quot;: &quot;#&quot;,
        ///        &quot;icon&quot;: &quot;glyphicon-stats&quot;,
        ///        &quot;subMenu&quot;: []
        ///    }.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;id&quot;: &quot;docsfiscais&quot;,
        ///        &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///        &quot;isActive&quot;: true,
        ///        &quot;name&quot;: &quot;Documentos Fiscais&quot;,
        ///        &quot;link&quot;: &quot;/DocumentosFiscais&quot;,
        ///        &quot;icon&quot;: &quot;glyphicon glyphicon-duplicate&quot;,
        ///        &quot;subMenu&quot;: []
        ///    }.
        /// </summary>
        internal static string documentosfiscais {
            get {
                return ResourceManager.GetString("documentosfiscais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;fechamentos&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Fechamentos&quot;,
        ///                &quot;link&quot;: &quot;/Fechamento&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string fechamentos {
            get {
                return ResourceManager.GetString("fechamentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;grupos&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Grupos de Empresas&quot;,
        ///                &quot;link&quot;: &quot;/Grupos&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string grupos {
            get {
                return ResourceManager.GetString("grupos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;id&quot;: &quot;historico&quot;,
        ///        &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///        &quot;isActive&quot;: true,
        ///        &quot;name&quot;: &quot;Principal&quot;,
        ///        &quot;link&quot;: &quot;/Home&quot;,
        ///        &quot;icon&quot;: &quot;glyphicon glyphicon-home&quot;,
        ///        &quot;subMenu&quot;: []
        ///    }.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;valores-manuais&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Inserção de Saldos&quot;,
        ///                &quot;link&quot;: &quot;/ValoresManuais&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string InsercaoSaldos {
            get {
                return ResourceManager.GetString("InsercaoSaldos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;mensagens&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: false,
        ///                &quot;name&quot;: &quot;Mensagens&quot;,
        ///                &quot;link&quot;: &quot;/Mensagens&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string mensagens {
            get {
                return ResourceManager.GetString("mensagens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;perfil&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Perfis&quot;,
        ///                &quot;link&quot;: &quot;/Perfil&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///}.
        /// </summary>
        internal static string perfil {
            get {
                return ResourceManager.GetString("perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;permissoes&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Permissões&quot;,
        ///                &quot;link&quot;: &quot;/Permissoes&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///}.
        /// </summary>
        internal static string permissoes {
            get {
                return ResourceManager.GetString("permissoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;relatorios&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Relatórios&quot;,
        ///                &quot;link&quot;: &quot;/Relatorios&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string relatorios {
            get {
                return ResourceManager.GetString("relatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;saldosiniciais&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Saldos Iniciais&quot;,
        ///                &quot;link&quot;: &quot;/SaldosIniciais&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string saldosiniciais {
            get {
                return ResourceManager.GetString("saldosiniciais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;tarefas&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Exportação de Dados&quot;,
        ///                &quot;link&quot;: &quot;/Jobs&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string sisconfiggeral {
            get {
                return ResourceManager.GetString("sisconfiggeral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///        &quot;id&quot;: &quot;utilidades&quot;,
        ///        &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///        &quot;isActive&quot;: true,
        ///        &quot;name&quot;: &quot;Utilidades&quot;,
        ///        &quot;link&quot;: &quot;#&quot;,
        ///        &quot;icon&quot;: &quot;glyphicon-wrench&quot;,
        ///        &quot;subMenu&quot;: [.
        /// </summary>
        internal static string sistema {
            get {
                return ResourceManager.GetString("sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ 
        ///   {
        ///        &quot;id&quot;: &quot;configuracoes&quot;,
        ///        &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///        &quot;isActive&quot;: true,
        ///        &quot;name&quot;: &quot;Configurações&quot;,
        ///        &quot;link&quot;: &quot;/Config&quot;,
        ///        &quot;icon&quot;: &quot;glyphicon-cog&quot;,
        ///        &quot;subMenu&quot;: []
        ///    }
        ///].
        /// </summary>
        internal static string teste {
            get {
                return ResourceManager.GetString("teste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///                &quot;id&quot;: &quot;validacoes&quot;,
        ///                &quot;guid&quot;: &quot;cd003d17-db0e-4ff2-ab36-c2adbcdca85c&quot;,
        ///                &quot;isActive&quot;: true,
        ///                &quot;name&quot;: &quot;Validações&quot;,
        ///                &quot;link&quot;: &quot;/Validacoes&quot;,
        ///                &quot;icon&quot;: &quot;&quot;
        ///            }.
        /// </summary>
        internal static string validacoes {
            get {
                return ResourceManager.GetString("validacoes", resourceCulture);
            }
        }
    }
}
